name = "Custom Excel Templates Theme"
license = "MIT"
licenselink = "https://github.com/yourname/hugo-theme-custom/blob/master/LICENSE"
description = "A clean, modern theme for Excel template sharing websites"
homepage = "https://github.com/yourname/hugo-theme-custom"
tags = ["blog", "clean", "minimal", "modern", "responsive"]
features = ["responsive", "seo", "fast"]
min_version = "0.80.0"

[author]
  name = "Your Name"
  homepage = "https://yourwebsite.com"